routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'FrontController@index');

# раздел новостей на сайте #
Route::group(['prefix' => 'news', 'as' => 'news.'], function() {
    Route::get('/', 'FrontController@showNewsList');
    Route::get('{code}', 'FrontController@showNewsItem');
});

# раздел для ПК-игры и редактора #
Route::group(['prefix' => 'pc-game', 'as' => 'pc.'], function() {
    Route::get('/', 'FrontController@viewPcGameIndex')->name('index');
    Route::get('v{version}', 'FrontController@viewPcGameRelease')->name('release');

    Route::group(['prefix' => 'editor', 'as' => 'editor.'], function() {
        Route::get('v{version}', 'FrontController@viewQuestionsEditorRelease')->name('release');
    });
});

# руты для онлайн-игры
Route::group(['prefix' => 'online', 'as' => 'online.'], function() {
    Route::get('/', 'FrontController@onlineGameMainPage')->name('index');

    # а здесь будет описано всё то, что нужно будет для нормального функционирования игры
    ## OAUTH-авторизация
    Route::get('auth', 'OAuth\StartAuthorization@run');
    Route::get('register', 'OAuth\VerifyAuthorization@step1');

    ## переход к игре
    Route::group(['prefix' => 'game'], function() {
        Route::get('/', 'OnlineGameController@index')->name('app');

        Route::group(['prefix' => 'api', 'as' => 'api.'], function() {
            Route::post('get_player', 'OnlineGameController@getPlayer')->name('player');
            Route::post('complete_game', 'OnlineGameController@saveResults')->name('complete');
            Route::post('ping', 'OnlineGameController@makeAction')->name('ping');
            Route::post('top', 'OnlineGameController@getTopPlayers')->name('top');
        });
    });
});

# Admin panel routes | Registration is not available #
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

Route::group(['prefix' => 'adm', 'as' => 'admin.'], function() {
    Route::get('/first', 'AdminController@index')->name('dashboard');

    Route::group(['prefix' => 'news', 'as' => 'news.'], function() {
        Route::get('add', 'AdminController@addNewsItem')->name('add');
        Route::post('add', 'AdminController@saveNewsItem');
    });

    Route::group(['prefix' => 'pages', 'as' => 'pages.'], function() {
        Route::get('add', 'AdminController@addNewPage')->name('add');
        Route::post('add', 'AdminController@saveNewPage');
    });

    Route::group(['prefix' => 'pc_releases', 'as' => 'pc_game.'], function () {
        Route::get('/', 'AdminController@listGameReleases')->name('list');
        Route::get('new', 'AdminController@newGameRelease')->name('new_release');
        Route::post('new', 'AdminController@createGameRelease');
    });

    Route::group(['prefix' => 'editor_releases', 'as' => 'qeditor.'], function() {
        Route::get('/', 'AdminController@listEditorReleases')->name('list');
        Route::get('new', 'AdminController@newEditorRelease')->name('new_release');
        Route::post('new', 'AdminController@createEditorRelease');
    });

    Route::group(['prefix' => 'online_stats', 'as' => 'online.'], function() {
        Route::get('/', 'AdminController@onlineGameStatsMain')->name('main');
    });

    Route::get('/settings', 'AdminController@getSettingsPage')->name('settings');
    Route::post('/settings', 'AdminController@saveSettingsPage');
});

# для страниц сайта на фронте #
Route::get('{slug}', 'FrontController@getPage');

resources/views/back/editor_releases/add.blade.php
@extends('layouts.admin')

@section('content')
    <div class="page-header">
        <div class="container-fluid">
            <h2 class="h5 no-margin-bottom">Релизы редактора вопросов / Создание нового релиза</h2>
        </div>
    </div>
    <section class="no-padding-top no-padding-bottom">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="block">
                        <div class="title"><strong>Данные нового релиза</strong></div>
                        <div class="block-body">
                            <form class="form-horizontal" method="POST" action="{{ route('admin.qeditor.new_release') }}" enctype="multipart/form-data">
                                {{ csrf_field() }}
                                <div class="form-group row">
                                    <label class="col-sm-3 form-control-label">Мажорная версия</label>
                                    <div class="col-sm-3">
                                        <input type="number" name="major_version" class="form-control" value="" placeholder="0" min="0" required>
                                    </div>
                                    <label class="col-sm-3 form-control-label">Минорная версия</label>
                                    <div class="col-sm-3">
                                        <input type="number" name="minor_version" class="form-control" value="" placeholder="0" min="0" required>
                                    </div>
                                </div>
                                <div class="line"></div>
                                <div class="form-group row">
                                    <label class="col-sm-3 form-control-label">Текстовый вариант версии</label>
                                    <div class="col-sm-9">
                                        <input type="text" name="version" class="form-control" readonly placeholder="0.00">
                                    </div>
                                </div>
                                <div class="line"></div>
                                <div class="form-group row">
                                    <label for="published_date" class="col-sm-3 form-control-label">Дата релиза:</label>
                                    <div class="col-sm-9">
                                        <input type="text" name="release_date" id="published_date" readonly value="" class="form-control">
                                    </div>
                                </div>
                                <div class="line"></div>
                                <div class="form-group row">
                                    <label class="col-sm-3 form-control-label" for="f_text">Описание релиза:</label>
                                    <div class="col-sm-9">
                                        <textarea id="f_text" name="description" class="form-control wswg" required></textarea>
                                    </div>
                                </div>
                                <div class="line"></div>
                                <div class="form-group row">
                                    <label class="col-sm-3 form-control-label">Ссылка на скачивание инсталлятора или файла:</label>
                                    <div class="col-sm-9">
                                        <input type="text" name="download_link" class="form-control" placeholder="относительно корня сайта, к примеру: /files/Install.msi">
                                    </div>
                                </div>
                                <div class="line"></div>
                                <div class="form-group row">
                                    <div class="col-sm-9 ml-auto">
                                        <button type="submit" class="btn btn-primary">Создать релиз игры</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <style>
        .bootstrap-datetimepicker-widget.dropdown-menu {
            display: block !important;
        }
    </style>
@endsection

@section('additional_scripts')
    <script>
        $(document).ready(function() {
            $('input[name="major_version"]').on('keyup', function() {
                $('input[name="version"]').val($('input[name="major_version"]').val() + '.' + $('input[name="minor_version"]').val());
            });
            $('input[name="minor_version"]').on('keyup', function() {
                $('input[name="version"]').val($('input[name="major_version"]').val() + '.' + $('input[name="minor_version"]').val());
            });
        });
    </script>
@endsection

resources/views/back/editor_releases/index.blade.php
@extends('layouts.admin')

@section('content')
    <div class="page-header">
        <div class="container-fluid">
            <a href="{{ route('admin.qeditor.new_release', [], false) }}" class="btn btn-primary btn-sm" style="float: right">Создать новый релиз</a>
            <h2 class="h5 no-margin-bottom">
                Релизы редактора вопросов
            </h2>
        </div>
    </div>
    <section class="no-padding-top no-padding-bottom">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="block">
                        <div class="table-responsive">
                            <table class="table table-striped table-hover">
                                <thead>
                                <tr>
                                    <th>Версия</th>
                                    <th>Дата релиза</th>
                                    <th>Ссылка на установщик / файл</th>
                                    <th>Размер</th>
                                    <th>Действия</th>
                                </tr>
                                </thead>
                                <tbody>
                                    @forelse($releasesList as $editorRelease)
                                        <tr>
                                            <th scope="row">{{ $editorRelease->version }}</th>
                                            <td>{{ date('d.m.Y', strtotime($editorRelease->release_date)) }}</td>
                                            <td><a target="_blank" href="{{ $editorRelease->download_link }}">Скачать</a></td>
                                            <td>{{ round($editorRelease->filesize / 1024. / 1024., 2) }} Mb</td>
                                            <td>
                                                —
                                            </td>
                                        </tr>
                                    @empty
                                        <tr>
                                            <td colspan="5" class="text-center">Нет ни одного релиза редактора вопросов!</td>
                                        </tr>
                                    @endforelse
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection